# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_latitude', models.CharField(max_length=128)),
                ('from_longitude', models.CharField(max_length=128)),
                ('to_latitude', models.CharField(max_length=128)),
                ('to_longitude', models.CharField(max_length=128)),
                ('pending', models.BooleanField(default=True)),
                ('book_date', models.DateField()),
                ('requestid', models.CharField(max_length=512, null=True)),
                ('productid', models.CharField(max_length=512, null=True)),
                ('surge_confirmation_id', models.CharField(max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
