# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_fare', models.FloatField()),
                ('min_fare_distance', models.FloatField()),
                ('fare_per_km', models.FloatField()),
                ('fare_per_min', models.FloatField()),
            ],
        ),
    ]
